### ISSUE TITLE
feat: implement https://www.petplace.com/newsletter-signup/

### ISSUE THREAD

**Issue by mfrisbey** [hlxsites/petplace#319]
![Image](https://user-images.githubusercontent.com/1235810/253618016-2e921522-f4d6-4924-aa93-88cbe9403efa.png)

**Comment by ankyc-phi** [comment]
hey guys, we're starting to see an issue with this page again - i took a look at #322 and #324, not sure if there have been any changes since - but the live site and staging site don't seem to show the form anymore on the newsletter signup page, please advise on what i can do to find a solution :)

https://main--petplace--hlxsites.hlx.page/newsletter-signup

**Comment by ankyc-phi** [comment]
https://github.com/hlxsites/petplace/commit/0df6d261d454102f930880f13639b25a41ac9b3d
